# basic config from https://hackernoon.com/monitor-your-infrastructure-with-tig-stack-b63971a15ccf
# [matisku] = additional config from https://github.com/matisku/tig-stack
version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.5
    #image: influxdb:1.0.2
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
        INFLUX_DATABASE:   "telegraf"   # [matisku]
        INLFUX_ADMIN_USER: "grafana"
        INFLUX_ADMIN_PASS: "grafana"    # ++ FIXME docker yml password solution?
    volumes:
      - /opt/tig/influxdb:/var/lib/influxdb
      #- /home/core/volumes/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:5.1.5
    #image: grafana/grafana:4.3.2
    ports:
      - "3000:3000"
    links:
      - influxdb
    environment: # [matisku ]
        ##GF_SECURITY_ADMIN_USER: admin
        #GF_SECURITY_ADMIN_PASSWORD: admin ## ++ FIXME 
        ##GF_SECURITY_ADMIN_PASSWORD: adminadmin  ## changed on webui, thus not setting it again.
        GF_SECURITY_SECRET_KEY: grafana
        GF_USERS_ALLOW_SIGN_UP: "true"
        GF_USERS_ALLOW_ORG_CREATE: "true"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_NAME: grafana
        GF_DASHBOARDS_JSON_ENABLED: "true"
        #GF_DASHBOARDS_JSON_PATH: /opt/grafana
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:1.5
    #image: telegraf:1.3.3
    network_mode: "host"
    environment:
        #HOST_NAME:     "telegraf"   # [mutisku]
        HOST_NAME:     "localhost"   
        #INFLUXDB_HOST: "influxdb"
        INFLUXDB_HOST: "localhost"
        INFLUXDB_PORT: "8086"
        DATABASE:      "telegraf"
    volumes:
      - /home/tin/tin-gh/inet-dev-class/tig/conf/telegraf.conf:/etc/telegraf/telegraf.conf
      #- /opt/tig/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      #- /home/core/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
