---

## child_play.yml
## expect to be called by a parent, eg cs2prime_play.yml
## making this a playbook rather than an include task list so that it is 
## independently runnable if/when necessary

- hosts: localhost and all

  vars:
     - SrcBaseDir: /tmp/tin/src
     - DstBaseDir: /tmp/tin/dst

  tasks:
    - name: "record kernel version into a variable"
      shell: uname -r
      register: kernel

    - block: 
        - name: "Ensure source and dest dir exist"
          file: 
                path: /tmp/tin/src
                state: directory
        - file: 
                path: /tmp/tin/dst
                state: directory

        - name: "Place a marker file to track Ansile run progress"
          file: 
                path: /tmp/tin/AnsibleRun
                state: directory
        - file: 
                path: /tmp/tin/AnsibleRun/child_play.marker
                state: touch

        - name: "record kernel version into a variable"
          shell: "dmesg > /tmp/tin/src/dmesg.log"
        - shell: "uname -a > /tmp/tin/src/example.log"

        # src: is local host path (ie where ansible is invoked)
        # dest: is remote manachine ansible is managing 
        # but if "localhost", then they may become the same!?
        - name: "copy dummy log"
          copy:
              #src:  "{{ SrcBaseDir }}/dmesg.log"
              src:  "{{ SrcBaseDir }}/example.log"
              dest: "{{ DstBaseDir }}"
              mode: 0600
              backup: yes


