---

# yaml file to configure bofh, a fedora 25 machine
# cueball is the ansible "controller"
# root@cueball:/root/.ssh/id_rsa_sinclave.pub > root@bofh:/root/.ssh/authorized_keys 
# root@cueball : ln -s id_rsa_sinclave id_rsa
# 2017.11

# vi use
# : set shiftwidth=2 tabstop=4 expandtab list nu ft=ruby
# : retab 
# : syntax on 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# check syntax: 
# ansible-playbook bofh_playbook.yml --syntax-check
# ?? ansible-playbook -i tests/inventory tests/$SITE --syntax-check
#
# test with: 
# ?? ansible -h sn_inventory.ini -m setup
# ansible localhost -m setup                # see all pre-defined ansible variables
#
# actually run it:
# - sudo ansible-playbook      bofh_playbook.yml -i inventory.ini
# - sudo ansible-playbook -vvv bofh_playbook.yml -i inventory.ini       
#    -v   adds little.  -vv is okay for run time troubleshooting.   -vvv for dev that show task data structure (all arguments), run ssh w/ -v
#    (bofh is the only host defined in inventory.ini at this time)
#    only root has ssh key setup, thus need to use sudo.  ansible login to remote host first then use "become"
#    bofh need python installed
# - ansible workstation -i inventory.ini -m command --args "uptime"           # ad-hoc command test
#   (bofh is the only host defined under workstation group at this time)

# ~~~~

# yaml quirky: 
# --- means start of doc
# ... means end of doc (but often not seen)
# like python, space matter!  it dictates the hierarchy
# worse than python, yaml say not to use space in the beginning of line to do indentation/blocking level.
# and with the use of '-', yeah, it is a mess!!

#    but the "-" to define list has to stick out for visibility.  this make shifting block level a real PITA  !!!! :( 
#    Not sure when need to use "-" and when don't.  Best to use 4 space tab even for "-" and the next/prev block
#    especially when the "when" clause is at the end of the block!!


# ~~~~

#- hosts: ansible_os_family == "RedHat" # this don't work.  
#- hosts: all
- hosts: bofh 
  become: true  # not really needed, cuz use "sudo ansible-playbook..." and so running as root already
  roles: 
      - gui_workstation.yml   # add X11, MATE desktop env     # this space not doing anything (yet)  ++FIXME++
      #- sn_pkg.yml            # add my favorite packages
  tasks:
      - debug:
          msg: This is a debug message from bofh_playbook.yml [L56]
          msg: This is a debug message from bofh_playbook.yml [L57]  # this msg def overwrite above
      - debug:
          msg: 'debug cannot handle a list, thus cannot "- msg" above for multiple entry, must add additional "- debug" clause.'

      - include_tasks: infra_cf.yml
      - import_tasks:  dev_tool.yml                   # both yml are included, so far so good :)
      - import_tasks:  "gui_workstation.yml"          # let this handle OS platform, as some commands could be platform independent
      - import_tasks:  epel.yml                       # actually want to put this at the end to avoid other depending on epel...
      - import_tasks:  os_update_redhat.yml   
      #- include_tasks: "os_upgrade_redhat_6to7.yml"   # just to try on bofh (centos6 desktop) to see if it works...

      - name: Set hostname to bofh...  POTENTIALLY DANGEROUS 
        block:
        - hostname:
            name: bofh
        when: ansible_hostname == "bofh2"
        # list of ansible pre-def vars: https://stackoverflow.com/questions/18839509/where-can-i-get-a-list-of-ansible-pre-defined-variables
        # ansible localhost -m setup | less

      - name: Find out architecture-independent kernel name
        shell: uname -r | sed 's/-[az].*$//'
        register: kernel_common

      - name: add my favorite users :)
        #shell: uptime   # dummy for now
      # http://docs.ansible.com/ansible/latest/user_module.html
        # no "-" in front of each user clause means only add last user!!
        # but "- user:" cause error, so no way to add multiple user in a single name clause?  F'ing YAML!! or F'ing Ansible??!! !@#$
        user:           # will make home dir as well
            name:       tin
            comment:    sn
            group:      wheel
            uid:        43413 
            shell:      /bin/bash

      - name: "add my favorite user #2 :)"
        user:           # will make home dir as well
            name:       berkeley
            comment:    berkeley
            group:      users
            uid:        1595256 
            shell:      /bin/bash

